server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.211.99:3306/codespace?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Fhl0009252937#
  mvc:
    pathmatch:
      #springboot 集成Swagger2报错原因：
      #这是因为Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher。
      matching-strategy: ant_path_matcher

#mvc:
#pathmatch:
#matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath*:/mappers/*.xml
  type-aliases-package: xxx.xxxx.xxx.xxx


#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true

